/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 24-сен-2024 10:14:00 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Tables */

DROP TABLE IF EXISTS bc_group CASCADE
;

DROP TABLE IF EXISTS groups CASCADE
;

DROP TABLE IF EXISTS maps CASCADE
;

DROP TABLE IF EXISTS tc_group CASCADE
;

DROP TABLE IF EXISTS user_map CASCADE
;

/* Create Tables */

CREATE TABLE bc_group
(
	id integer NOT NULL,
	bc_id integer NOT NULL,
	group_id integer NOT NULL
)
;

CREATE TABLE groups
(
	id integer NOT NULL,
	name varchar(100) NOT NULL,
	map_id integer NOT NULL,
	parent_id varchar(50) NULL
)
;

CREATE TABLE maps
(
	id integer NOT NULL,
	description varchar(250) NULL,
	name varchar(100) NOT NULL,
	create_date timestamp without time zone NOT NULL,
	update_date timestamp without time zone NULL,
	deleted_date timestamp without time zone NULL,
	type_id integer NOT NULL
)
;

CREATE TABLE tc_group
(
	id integer NOT NULL,
	tc_id integer NOT NULL,
	group_id integer NOT NULL
)
;

CREATE TABLE user_map
(
	id integer NOT NULL,
	user_id integer NOT NULL,
	map_id integer NOT NULL,
	author boolean NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE bc_group ADD CONSTRAINT pk_bc_group
	PRIMARY KEY (id)
;

CREATE INDEX ix_bc_group_groups ON bc_group (group_id ASC)
;

CREATE INDEX ixfk_bc_group_business_capability ON bc_group (bc_id ASC)
;

ALTER TABLE groups ADD CONSTRAINT pk_groups
	PRIMARY KEY (id)
;

CREATE INDEX ixfk_groups_maps ON groups (map_id ASC)
;

ALTER TABLE maps ADD CONSTRAINT pk_maps
	PRIMARY KEY (id)
;

CREATE INDEX ixfk_maps_entity_type ON maps (type_id ASC)
;

ALTER TABLE tc_group ADD CONSTRAINT pk_tc_group
	PRIMARY KEY (id)
;

CREATE INDEX ixfk_tc_group_groups ON tc_group (group_id ASC)
;

CREATE INDEX ixfk_tc_group_tech_capability ON tc_group (tc_id ASC)
;

ALTER TABLE user_map ADD CONSTRAINT pk_id
	PRIMARY KEY (id)
;

CREATE INDEX ixfk_user_map_maps ON user_map (map_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE bc_group ADD CONSTRAINT fk_bc_group_business_capability
	FOREIGN KEY (bc_id) REFERENCES business_capability (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE bc_group ADD CONSTRAINT fk_bc_group_groups
	FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE groups ADD CONSTRAINT fk_groups_maps
	FOREIGN KEY (map_id) REFERENCES maps (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE maps ADD CONSTRAINT fk_maps_entity_type
	FOREIGN KEY (type_id) REFERENCES entity_type (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE tc_group ADD CONSTRAINT fk_tc_group_groups
	FOREIGN KEY (group_id) REFERENCES groups (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE tc_group ADD CONSTRAINT fk_tc_group_tech_capability
	FOREIGN KEY (tc_id) REFERENCES tech_capability (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE user_map ADD CONSTRAINT fk_user_map_maps
	FOREIGN KEY (map_id) REFERENCES maps (id) ON DELETE No Action ON UPDATE No Action
;
