/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1 		*/
/*  Created On : 29-июл-2024 10:16:47 				*/
/*  DBMS       : PostgreSQL 						*/
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS sequence_criterion_bc_id
;

DROP SEQUENCE IF EXISTS sequence_criterion_tc_id
;

DROP SEQUENCE IF EXISTS sequence_seq_id
;

DROP SEQUENCE IF EXISTS sequence_seq_tc_id
;

/* Drop Tables */

DROP TABLE IF EXISTS criterias_bc CASCADE
;

DROP TABLE IF EXISTS criterias_tc CASCADE
;

DROP TABLE IF EXISTS enum_criterias CASCADE
;

DROP TABLE IF EXISTS sequence CASCADE
;

DROP TABLE IF EXISTS sequence_tc CASCADE
;

/* Create Tables */

CREATE TABLE criterias_bc
(
    id integer NOT NULL   DEFAULT NEXTVAL(('sequence_criterion_bc_id'::text)::regclass),
    criterion_id integer NOT NULL,
    value integer NOT NULL,
    grade integer NULL,
    bc_id integer NOT NULL
)
;

CREATE TABLE criterias_tc
(
    id integer NOT NULL   DEFAULT NEXTVAL(('sequence_criterion_tc_id'::text)::regclass),
    criterion_id integer NOT NULL,
    value integer NOT NULL,
    grade integer NULL,
    tc_id integer NOT NULL
)
;

CREATE TABLE enum_criterias
(
    id integer NOT NULL,
    name varchar(150) NOT NULL,
    type varchar(50) NOT NULL,
    interval integer NULL,
    threshold integer NULL
)
;

CREATE TABLE sequence
(
    id integer NOT NULL   DEFAULT NEXTVAL(('sequence_seq_id'::text)::regclass),
    name varchar(50) NOT NULL,
    link varchar(100) NOT NULL
)
;

CREATE TABLE sequence_tc
(
    id integer NOT NULL   DEFAULT NEXTVAL(('sequence_seq_tc_id'::text)::regclass),
    seq_id integer NOT NULL,
    tc_id integer NOT NULL
)
;

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE criterias_bc ADD CONSTRAINT pk_criterias_bc
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_criterias_bc_business_capability ON criterias_bc (bc_id ASC)
;

CREATE INDEX ixfk_criterias_bc_enum_criterias ON criterias_bc (criterion_id ASC)
;

ALTER TABLE criterias_tc ADD CONSTRAINT pk_criterias_tc
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_criterias_tc_enum_criterias ON criterias_tc (criterion_id ASC)
;

CREATE INDEX ixfk_criterias_tc_tech_capability ON criterias_tc (tc_id ASC)
;

ALTER TABLE enum_criterias ADD CONSTRAINT pk_enum_criterias
    PRIMARY KEY (id)
;

ALTER TABLE sequence ADD CONSTRAINT pk_sequence
    PRIMARY KEY (id)
;

ALTER TABLE sequence_tc ADD CONSTRAINT pk_sequence_tc
    PRIMARY KEY (id)
;

CREATE INDEX ixfk_sequence_tc_sequence ON sequence_tc (seq_id ASC)
;

CREATE INDEX ixfk_sequence_tc_tech_capability ON sequence_tc (tc_id ASC)
;

/* Create Foreign Key Constraints */

ALTER TABLE criterias_bc ADD CONSTRAINT fk_criterias_bc_business_capability
    FOREIGN KEY (bc_id) REFERENCES business_capability (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE criterias_bc ADD CONSTRAINT fk_criterias_bc_enum_criterias
    FOREIGN KEY (criterion_id) REFERENCES enum_criterias (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE criterias_tc ADD CONSTRAINT fk_criterias_tc_enum_criterias
    FOREIGN KEY (criterion_id) REFERENCES enum_criterias (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE criterias_tc ADD CONSTRAINT fk_criterias_tc_tech_capability
    FOREIGN KEY (tc_id) REFERENCES tech_capability (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sequence_tc ADD CONSTRAINT fk_sequence_tc_sequence
    FOREIGN KEY (seq_id) REFERENCES sequence (id) ON DELETE No Action ON UPDATE No Action
;

ALTER TABLE sequence_tc ADD CONSTRAINT fk_sequence_tc_tech_capability
    FOREIGN KEY (tc_id) REFERENCES tech_capability (id) ON DELETE No Action ON UPDATE No Action
;

/* Create Table Comments, Sequences for Autonumber Columns */

CREATE SEQUENCE sequence_criterion_bc_id INCREMENT 1 START 1
;

CREATE SEQUENCE sequence_criterion_tc_id INCREMENT 1 START 1
;

CREATE SEQUENCE sequence_seq_id INCREMENT 1 START 1
;

CREATE SEQUENCE sequence_seq_tc_id INCREMENT 1 START 1
;
