/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 16.1     */
/*  Created On : 20-ноя-2024 16:45:10         */
/*  DBMS       : PostgreSQL             */
/* ---------------------------------------------------- */

/* Drop Sequences for Autonumber Columns */

DROP SEQUENCE IF EXISTS seq_entity_type_id;

/* Create Sequences for Autonumber Columns */

CREATE SEQUENCE seq_entity_type_id INCREMENT 1 START 1;

/* Drop Tables */

DROP TABLE IF EXISTS entity_type CASCADE;

/* Create Tables */

CREATE TABLE entity_type
(
    id integer NOT NULL DEFAULT NEXTVAL('seq_entity_type_id'),
    name varchar(50) NOT NULL,
    title varchar(50) NOT NULL
);

/* Create Primary Keys, Indexes, Uniques, Checks */

ALTER TABLE entity_type ADD CONSTRAINT pk_entity_type
    PRIMARY KEY (id);

/* Insert Data */

INSERT INTO entity_type (name, title)
VALUES
    ('TECH_CAPABILITY', 'Технические возможности'),
    ('BUSINESS_CAPABILITY', 'Бизнес-возможности');