DO $$
DECLARE
rec RECORD;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM capability.business_capability) THEN
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 4, 'GRP.000', 'Каталог Возможностей (Capability Catalog)', 'Общий каталог возможностей. Включает группы доменов и домены L2 ФДМ.', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', null, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 5, 'GRP.001', 'Нефтегазовая Разведка', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 4, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 6, 'DMN.001', 'Оценка возможностей', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 5, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 7, 'BC.00001', 'Геологическая и геофизическая идентификация и отбор', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 6, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 8, 'BC.00002', 'Выявление и развитие возможностей добычи нефти и газа', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 6, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 9, 'BC.00003', 'Выявление и развитие перспективных нефтегазовых месторождений', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 6, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 10, 'DMN.002', 'Геологический и географический анализ', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 5, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 11, 'BC.00004', 'Геопространственный анализ данных', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 10, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 12, 'BC.00005', 'Дистанционный анализ', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 10, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 13, 'BC.00006', 'Петрофизический анализ', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 10, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 14, 'BC.00007', 'Микроскопический и визуальный анализ', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 10, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 15, 'BC.00008', 'Характеризация капиллярного давления', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 10, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 147, 'BC.00009', 'Геохимический анализ', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 10, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 16, 'DMN.003', 'Разведочное бурение', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 5, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 17, 'BC.00010', 'Морские буровые операции', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 16, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 18, 'BC.00011', 'Наземные буровые операции', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 16, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 19, 'BC.00012', 'Управление разрешением на разведку', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 16, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 20, 'DMN.004', 'Оценка активов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 5, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 21, 'BC.00013', 'Оценка резервуаров и недр', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 20, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 22, 'BC.00014', 'Оценка потенциала производства', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 20, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 23, 'BC.00015', 'Экономическое обоснование', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 20, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 24, 'BC.00016', 'Техническая и операционная целесообразность', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 20, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 25, 'BC.00017', 'Анализ рисков и неопределенностей', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 20, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 26, 'BC.00018', 'Оценка рисков экологического и социального воздействия', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 20, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 27, 'DMN.005', 'Согласование контрактов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 5, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 28, 'BC.00091', 'Управление контрактами на раздел продукции', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 27, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 29, 'BC.00019', 'Управление контрактами на нефтепромысловые услуги и оборудование', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 27, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 30, 'BC.00020', 'Hазработка соглашений о совместном предприятии и партнерстве', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 27, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 31, 'BC.00021', 'Управление контрактами на продажу и маркетинг углеводородов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 27, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 32, 'BC.00022', 'Администрирование контрактов на бурение', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 27, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 33, 'DMN.006', 'Управление венчурным финансированием', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 5, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 34, 'BC.00023', 'Cодействие созданию и управлению совместными предприятиями', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 33, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 35, 'BC.00024', 'Государственное лицензирование и разрешение', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 33, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 36, 'BC.00025', 'Оценка концессионного соглашения', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 33, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 37, 'BC.00026', 'Лицензирование и управление разведкой', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 33, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 38, 'GRP.002', 'Производство и эксплуатация', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 4, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 39, 'DMN.007', 'Управление земельными ресурсами', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 38, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 40, 'BC.00027', 'Управление сельскохозяйственными землями', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 39, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 41, 'BC.00028', 'Управление лесными землями', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 39, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 42, 'BC.00029', 'Управление и согласование аренды земель', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 39, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 43, 'BC.00030', 'Исследование и анализ сделок с землей ', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 39, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 44, 'BC.00031', 'Управление собственностью земель и распределением доходов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 39, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 45, 'BC.00032', 'Картографирование и визуализация земельных участков', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 39, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 46, 'DMN.008', 'Моделирование мощностей', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 38, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 47, 'BC.00033', 'Оценка пропускной способности нефтегазовых месторождений', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 46, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 48, 'BC.00034', 'Моделирование объема и анализ сценариев', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 46, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 49, 'BC.00035', 'Оптимизация нефтегазовой техники', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 46, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 50, 'DMN.009', 'Контроль за разработкой месторождения', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 38, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 51, 'BC.00036', 'Мониторинг нефтяных и газовых пластов и недр', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 50, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 52, 'BC.00037', 'Оптимизация добычи нефти и газа на скважинах', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 50, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 53, 'BC.00038', 'Мониторинг датчиков и манометров нефти и газа', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 50, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 54, 'BC.00039', 'Оптимизация пропускной способности ', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 50, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 55, 'DMN.010', 'Программа бурения', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 38, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 56, 'BC.00040', 'Планирование и проектирование бурения', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 55, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 57, 'BC.00041', 'Мониторинг и оптимизация насосов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 55, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 58, 'BC.00042', 'Мониторинг и контроль закачки газа', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 55, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 59, 'BC.00043', 'Управление заводнения и дренажа', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 55, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 60, 'BC.00044', 'Анализ пластового давления', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 55, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 61, 'BC.00045', 'Планирование парка техники и координация ресурсов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 55, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 62, 'BC.00046', 'Контроль за скважиной и реагирование на инциденты', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 55, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 63, 'DMN.011', 'Планирование, строительство и бюджетирование скважин', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 38, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 64, 'BC.00047', 'Оценка стоимости скважин и бюджетирование', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 63, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 65, 'BC.00048', 'Проектирование насосно-компрессорных труб и окончания скважин', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 63, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 66, 'BC.00049', 'Оценка операционной эффективности', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 63, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 67, 'BC.00050', 'Оценка надежности скважин и оценка рисков', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 63, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 68, 'DMN.012', 'Эксплуатация и техническое обслуживание', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 38, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 69, 'BC.00051', 'Операции с использованием технологий', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 68, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 70, 'BC.00052', 'Координация технического обслуживания и ремонта', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 68, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 71, 'BC.00053', 'Мониторинг государственных  обязательств', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 68, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 72, 'BC.00054', 'Надзор за концессионным соглашением', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 68, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 73, 'GRP.003', 'Транспортировка нефти и газа', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 4, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 74, 'DMN.013', 'Управление контрактами', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 73, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 75, 'BC.00055', 'Планирование переговоров', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 74, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 76, 'BC.00056', 'Переговоры', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 74, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 77, 'BC.00057', 'Оценка и управление рисками', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 74, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 78, 'BC.00058', 'Обеспечение соблюдения требований законодательства', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 74, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 79, 'DMN.014', 'Управление логистикой', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 73, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 80, 'BC.00059', 'Логистическое планирование', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 79, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 81, 'BC.00060', 'Логистические операции', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 79, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 82, 'BC.00061', 'Оптимизация логистики', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 79, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 83, 'BC.00062', 'Мультимодальная оценка логистики', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 79, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 84, 'BC.00063', 'Эксплуатация нефтегазовых судов (танкеры, платформы и т.д.)', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 79, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 85, 'BC.00064', 'Управление терминалами', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 79, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 86, 'DMN.015', 'Управление цепочками поставок', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 73, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 87, 'BC.00065', 'Управление международными перевозками', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 86, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 88, 'BC.00066', 'Заказ нефти и газа', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 86, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 89, 'BC.00067', 'Торговля нефтью и газом', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 86, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 90, 'BC.00068', 'Планирование спроса для поставки нефти и газа', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 86, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 91, 'DMN.016', 'Управление земельными участками для транспортировки', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 73, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 92, 'BC.00069', 'Переговоры о присвоении земель для добычи нефти и газа', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 91, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 93, 'BC.00070', 'Операции по управлению землями в нефтегазовой отрасли', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 91, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 94, 'BC.00071', 'Земляные работы для прокладки трубопроводов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 91, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 95, 'BC.00072', 'Управление осушением', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 91, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 96, 'BC.00073', 'Послестроительная реставрация', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 91, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 97, 'DMN.017', 'Проектирование трубопроводов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 73, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 98, 'BC.00074', 'Инженерное проектирование трубопроводов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 97, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 99, 'BC.00075', 'Cоблюдение региональных кодексов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 97, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 100, 'BC.00076', 'Поиск материалов для трубопроводов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 97, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 101, 'BC.00077', 'Испытания  трубопроводов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 97, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 102, 'DMN.018', 'Строительство трубопроводов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 73, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 103, 'BC.00078', 'Управление местами размещения и хранения строительных материалов и оборудования', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 102, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 104, 'BC.00079', 'Вырубка земельных участков и земляные работы для прокладки трубопроводов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 102, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 105, 'BC.00080', 'Испытания и оценка качества работ', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 102, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 106, 'BC.00081', 'Ремонт трубопроводов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 102, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 107, 'BC.00082', 'Сборка трубопроводов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 102, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 108, 'BC.00083', 'Обслуживание пробопроводов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 102, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 109, 'DMN.019', 'Эксплуатация трубопроводов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 73, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 110, 'BC.00084', 'Экстренное реагирование', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 109, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 111, 'BC.00085', 'Мониторинг хранения и распространения', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 109, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 112, 'BC.00086', 'Инспектирование трубопроводов', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 109, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 113, 'BC.00087', 'Сутниковое инспектирование', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 109, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 114, 'BC.00088', 'Инспектирование дронами', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 109, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 115, 'BC.00089', 'Управление патрулированием', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 109, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 116, 'BC.00090', 'Наблюдаемость хранения и распределения для планирования спроса на местном уровне', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 109, '', '', false, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 117, 'GRP.004', 'Очистка и переработка нефти и газа', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 4, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 118, 'GRP.005', 'Маркетинг и дистрибуция продуктов нефти и газа', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 4, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 119, 'GRP.006', 'Основные общие возможности', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 4, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 120, 'DMN.020', 'Рыночный и экономический анализ', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 119, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 121, 'DMN.021', 'Управление партнерами', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 119, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 122, 'DMN.022', 'Управление программами проектов и проектами', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 119, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 123, 'DMN.023', 'Управление цепочками поставок', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 119, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 124, 'DMN.024', 'Управление качеством', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 119, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 125, 'DMN.025', 'Управление знаниями', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 119, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 126, 'DMN.026', 'Управление устойчивым развитием', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 119, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 127, 'DMN.027', 'Бизнес-аналитика', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 119, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 128, 'DMN.028', 'Управление изменениями', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 119, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 129, 'DMN.029', 'Отчетность по резервам', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 119, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 130, 'DMN.030', 'Управление соответствием (комплаенс)', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 119, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 131, 'DMN.031', 'Управление данными предприятия', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 119, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 132, 'DMN.032', 'Инновации и сотрудничества', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 119, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 133, 'DMN.033', 'Аккаунт менеджмент', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 119, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 134, 'DMN.034', 'Управление разработкой месторождений нефти и газа', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 119, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 135, 'DMN.035', 'Управление процессами и работами', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 119, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 136, 'GRP.007', 'Поддерживающие возможности', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 4, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 137, 'DMN.036', 'Стратегическое планирование', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 136, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 138, 'DMN.037', 'Управление людскими ресурсами', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 136, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 139, 'DMN.038', 'Управление рисками', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 136, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 140, 'DMN.039', 'Корпоративные финансы', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 136, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 141, 'DMN.040', 'Управление закупками', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 136, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 142, 'DMN.041', 'Управление портфолио', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 136, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 143, 'DMN.042', 'Юридические сервисы', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 136, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 144, 'DMN.043', 'Корпоративное управление', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 136, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 145, 'DMN.044', 'Корпоративная архитектура', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 136, '', '', true, '');
INSERT INTO capability.business_capability (id, code, name, description, owner, created_date, last_modified_date, deleted_date, status, parent_id, author, link, is_domain, source) VALUES ( 146, 'DMN.045', 'Управление ИТ', '', '', to_timestamp('09-12-2025 00:00:00','DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 'Proposed', 136, '', '', true, '');

PERFORM setval('capability.bc_id_seq', 150);

FOR rec IN
SELECT id, code, name, description
FROM capability.business_capability
WHERE id IN (
             4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 147,
             16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
             27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37,
             38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
             49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59,
             60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70,
             71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
             82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92,
             93, 94, 95, 96, 97, 98, 99, 100, 101, 102,
             103, 104, 105, 106, 107, 108, 109, 110, 111,
             112, 113, 114, 115, 116, 117, 118, 119, 120,
             121, 122, 123, 124, 125, 126, 127, 128, 129,
             130, 131, 132, 133, 134, 135, 136, 137, 138,
             139, 140, 141, 142, 143, 144, 145, 146
    )
    LOOP
INSERT INTO capability.find_name_sort_table (id, vector, type_id, id_ref)
VALUES (
    nextval('capability.find_name_sort_table_id_seq'),
    rec.name || '<!!!>' || COALESCE(rec.description, '') || '<!!!>' || rec.code,
    2,
    rec.id
    );
END LOOP;

END IF;
END $$;